# Generated by Django 3.2.12 on 2022-02-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleID', models.AutoField(db_column='roleID', primary_key=True, serialize=False)),
                ('roleName', models.CharField(db_column='roleName', max_length=30)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Securityquestions',
            fields=[
                ('securityQuestionID', models.AutoField(db_column='securityQuestionID', primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SecurityQuestions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, db_column='firstName', max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, db_column='lastName', max_length=50, null=True)),
                ('phoneNumber', models.DecimalField(blank=True, db_column='phoneNumber', decimal_places=0, max_digits=10, null=True)),
                ('postalAddress', models.CharField(blank=True, db_column='postalAddress', max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(db_column='userName', max_length=100)),
                ('pwd', models.CharField(max_length=32)),
                ('securityQuestionOneAnswer', models.CharField(blank=True, db_column='securityQuestionOneAnswer', max_length=30, null=True)),
                ('securityQuestionTwoAnswer', models.CharField(blank=True, db_column='securityQuestionTwoAnswer', max_length=30, null=True)),
                ('securityQuestionThreeAnswer', models.CharField(blank=True, db_column='securityQuestionThreeAnswer', max_length=30, null=True)),
                ('roleID', models.ForeignKey(db_column='roleID', on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
                ('securityQuestionOneID', models.ForeignKey(blank=True, db_column='securityQuestionOneID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q1', to='api.securityquestions')),
                ('securityQuestionThreeID', models.ForeignKey(blank=True, db_column='securityQuestionThreeID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q3', to='api.securityquestions')),
                ('securityQuestionTwoID', models.ForeignKey(blank=True, db_column='securityQuestionTwoID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q2', to='api.securityquestions')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('requestID', models.IntegerField(db_column='requestID', primary_key=True, serialize=False)),
                ('patientFirstName', models.CharField(db_column='patientFirstName', max_length=50)),
                ('patientLastName', models.CharField(db_column='patientLastName', max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('dateOfBirth', models.DateField(db_column='dateOfBirth')),
                ('locationOfService', models.CharField(db_column='locationOfService', max_length=30)),
                ('patientPhoneNumber', models.DecimalField(db_column='patientPhoneNumber', decimal_places=0, max_digits=10)),
                ('patientEmail', models.CharField(db_column='patientEmail', max_length=100)),
                ('serviceType', models.CharField(db_column='serviceType', max_length=10)),
                ('daysRequested', models.CharField(blank=True, db_column='daysRequested', max_length=10, null=True)),
                ('startTime', models.TimeField(blank=True, db_column='startTime', null=True)),
                ('endTime', models.TimeField(blank=True, db_column='endTime', null=True)),
                ('numDaysRequested', models.IntegerField(blank=True, db_column='numDaysRequested', null=True)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'db_table': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Healthcareprofessional',
            fields=[
                ('pid', models.IntegerField(db_column='PID', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='firstName', max_length=50)),
                ('lastName', models.CharField(db_column='lastName', max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('SSN', models.DecimalField(db_column='SSN', decimal_places=0, max_digits=9)),
                ('Type_H_S', models.CharField(db_column='Type_H_S', max_length=15)),
                ('Qualification', models.CharField(db_column='Qualification', max_length=10)),
                ('Qualification_Date', models.DateField(db_column='Qualification_Date')),
                ('Year_O_Exp', models.IntegerField(db_column='Year_O_Exp')),
                ('phoneNumber', models.DecimalField(blank=True, db_column='phoneNumber', decimal_places=0, max_digits=10, null=True)),
                ('postalAddress', models.CharField(blank=True, db_column='postalAddress', max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('enroll', models.TextField(blank=True, null=True)),
                ('userID', models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'db_table': 'HealthcareProfessional',
            },
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('takerID', models.AutoField(db_column='takerID', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='firstName', max_length=50)),
                ('lastName', models.CharField(db_column='lastName', max_length=50)),
                ('phoneNumber', models.DecimalField(blank=True, db_column='phoneNumber', decimal_places=0, max_digits=10, null=True)),
                ('postalAddress', models.CharField(blank=True, db_column='postalAddress', max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('enroll', models.TextField(blank=True, null=True)),
                ('userID', models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'db_table': 'CareTaker',
            },
        ),
    ]
