# Generated by Django 3.2.12 on 2022-02-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('AdID', models.AutoField(db_column='AdID', primary_key=True, serialize=False)),
                ('Type_H_S', models.CharField(db_column='Type_H_S', max_length=15)),
                ('Qualification', models.CharField(db_column='Qualification', max_length=10)),
                ('Year_O_Exp', models.IntegerField(db_column='Year_O_Exp')),
            ],
            options={
                'db_table': 'Advertise',
            },
        ),
    ]
