# Generated by Django 3.2.12 on 2022-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_advertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='enroll',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='enroll',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
