# Generated by Django 3.2.12 on 2022-02-28 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220228_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertise',
            old_name='Qualification',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='advertise',
            old_name='Type_H_S',
            new_name='typeHS',
        ),
        migrations.RenameField(
            model_name='advertise',
            old_name='Year_O_Exp',
            new_name='yearOExp',
        ),
        migrations.RenameField(
            model_name='healthcareprofessional',
            old_name='Qualification',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='healthcareprofessional',
            old_name='Type_H_S',
            new_name='typeHS',
        ),
        migrations.RenameField(
            model_name='healthcareprofessional',
            old_name='Year_O_Exp',
            new_name='yearOExp',
        ),
        migrations.RemoveField(
            model_name='healthcareprofessional',
            name='Qualification_Date',
        ),
        migrations.AddField(
            model_name='healthcareprofessional',
            name='qualificationDate',
            field=models.DateField(db_column='Qualification_Date', default=datetime.datetime.now),
        ),
    ]
