# Generated by Django 3.2.12 on 2022-02-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220228_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertise',
            old_name='AdID',
            new_name='adID',
        ),
    ]
