# Generated by Django 3.2.12 on 2022-02-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_adid_advertise_adid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcareprofessional',
            old_name='SSN',
            new_name='ssn',
        ),
    ]
