# Generated by Django 3.2.12 on 2022-02-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_ssn_healthcareprofessional_ssn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcareprofessional',
            old_name='pid',
            new_name='pID',
        ),
    ]
