# Generated by Django 3.2.12 on 2022-03-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_pid_healthcareprofessional_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprofessional',
            name='advertiseID',
            field=models.ForeignKey(blank=True, db_column='advertiseID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.advertise'),
        ),
    ]
