# Generated by Django 3.2.12 on 2022-03-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_healthcareprofessional_advertiseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='education',
            field=models.CharField(db_column='education', default='', max_length=100),
        ),
    ]
