# Generated by Django 3.2.12 on 2022-03-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_advertise_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareprofessional',
            name='advertiseID',
        ),
    ]
