# Generated by Django 3.2.12 on 2022-03-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_healthcareprofessional_advertiseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprofessional',
            name='advertiseID',
            field=models.ManyToManyField(blank=True, null=True, to='api.Advertise'),
        ),
    ]
