# Generated by Django 3.2.12 on 2022-03-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220301_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
