# Generated by Django 3.2.12 on 2022-03-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220303_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='adID',
            field=models.AutoField(db_column='adID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='qualification',
            field=models.CharField(db_column='qualification', max_length=10),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='typeHS',
            field=models.CharField(db_column='typeHS', max_length=15),
        ),
        migrations.AlterField(
            model_name='advertise',
            name='yearOExp',
            field=models.IntegerField(db_column='yearOExp'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_column='username', max_length=100),
        ),
    ]
