# Generated by Django 3.2.12 on 2022-03-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_requests_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='endTime',
            field=models.DateTimeField(blank=True, db_column='endTime', null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='startTime',
            field=models.DateTimeField(blank=True, db_column='startTime', null=True),
        ),
    ]
