# Generated by Django 3.2.12 on 2022-03-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220316_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='userID',
            field=models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthcareprofessional'),
        ),
    ]
