# Generated by Django 3.2.12 on 2022-03-16 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_requests_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.caretaker'),
        ),
    ]
