# Generated by Django 3.2.12 on 2022-03-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_userid_requests_hcpid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='requirements',
            field=models.JSONField(default=''),
        ),
    ]
