# Generated by Django 3.2.12 on 2022-03-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_requests_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprofessional',
            name='schedule',
            field=models.JSONField(default=''),
        ),
    ]
