# Generated by Django 3.2.12 on 2022-04-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_payment_schedulerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='hourlyRate',
            field=models.FloatField(default=100.0),
        ),
    ]
