# Generated by Django 3.2.12 on 2022-04-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220407_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
