# Generated by Django 3.2.12 on 2022-04-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20220407_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
