# Generated by Django 3.2.12 on 2022-04-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20220407_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='hcpPayedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='payedTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
