# Generated by Django 3.2.12 on 2022-04-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20220407_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
