# Generated by Django 3.2.12 on 2022-04-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20220407_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='user_from',
            new_name='userFrom',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='user_to',
            new_name='userTo',
        ),
    ]
