# Generated by Django 3.2.12 on 2022-04-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20220407_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
