# Generated by Django 3.2.12 on 2022-04-07 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220407_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='status',
            new_name='end',
        ),
    ]
