# Generated by Django 3.2.12 on 2022-04-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_rename_status_requests_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
