# Generated by Django 3.2.12 on 2022-04-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='hourlyRate',
            field=models.FloatField(blank=True, default=100.0, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.IntegerField(blank=True, help_text='0:申请,1:驳回,2:成功', null=True),
        ),
    ]
