# Generated by Django 3.2.12 on 2022-04-10 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20220408_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrecord',
            name='scheduleID',
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requests')),
            ],
            options={
                'db_table': 'BillingAccount',
            },
        ),
    ]
