# Generated by Django 3.2.12 on 2022-04-10 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20220410_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrecord',
            name='hasPayed',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='hcpPayed',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='hcpPayedTime',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='payedTime',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='salary',
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='paid',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='total',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paidTime', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('billingAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.billingaccount')),
            ],
            options={
                'db_table': 'PayRecord',
            },
        ),
    ]
