# Generated by Django 3.2.12 on 2022-04-10 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20220410_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaccount',
            name='category',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='amount',
        ),
        migrations.AddField(
            model_name='advertise',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='hcp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.healthcareprofessional'),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='unpaid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='healthcareprofessional',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='payrecord',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='requests',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='roles',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='securityquestions',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='users',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='billingaccount',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.requests'),
        ),
    ]
