# Generated by Django 3.2.12 on 2022-04-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20220411_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrecord',
            name='billingAccount',
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='billingAccount',
            field=models.JSONField(default={'paidTotal': 0.0, 'records': [], 'total': 0.0, 'unPaidTotal': 0.0}),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='salary',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='requests',
            name='billingAccount',
            field=models.JSONField(default={'paidTotal': 0.0, 'records': [], 'total': 0.0, 'unPaidTotal': 0.0}),
        ),
        migrations.DeleteModel(
            name='BillingAccount',
        ),
        migrations.DeleteModel(
            name='PayRecord',
        ),
    ]
