# Generated by Django 3.2.12 on 2022-04-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20220411_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
