# Generated by Django 3.2.12 on 2022-04-15 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_servicerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='userTo',
        ),
    ]
