# Generated by Django 3.2.12 on 2022-04-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_servicerequest_caretaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='id',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='serviceID',
            field=models.IntegerField(db_column='serviceID', default=1, primary_key=True, serialize=False),
        ),
    ]
