# Generated by Django 3.2.12 on 2022-04-15 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20220415_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='caretaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.caretaker'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='serviceID',
            field=models.IntegerField(db_column='serviceID', primary_key=True, serialize=False),
        ),
    ]
